name: Eleventy Build
on: [push]

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build
        uses: sasidhar/actions-eleventy@master
        with:
          args: --output dist
          install_dependencies: true
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          publish_dir: dist
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cname: rafa.sasidhar.com